hz: 10

dt: 0.05
predict_time: 0.8

goal_tolerance: 0.5

max_vel: 3.0
min_vel: 0.0
max_yawrate: 3.14159265359
min_yawrate: -3.14159265359
max_accel: 1000.0
max_dyawrate: 1000.0

v_reso: 0.05
y_reso: 0.05

heading_cost_gain: 1.0
velocity_cost_gain: 1.0
distance_cost_gain: 1.0

robot_radius: 0.25
radius_margin: 0.1

search_range: 0.95